### ISSUE TITLE
Ability to access outside of nock

### ISSUE THREAD

**Issue by jasonkuhrt** [octokit/fixtures#408]
We're writing E2E tests that mock the GH API. We have separate processes for all parts of the stack and just feed a URL to the app to a fake GH API. It would be great if fixtures from here we usable for this. The problem with nock is that it assumes the tests and the thing under test are running in the same process.

**Comment by gr2m** [comment]
we also have a standalone binary: https://github.com/octokit/fixtures-server

**Comment by jasonkuhrt** [comment]
Oh that looks very interesting, thanks. I think we were kind of going to reinvent this so great to know about it now!

**Comment by gr2m** [comment]
I’d also be open to add more fixtures/scenarios, or come up with a way to easily record and use your own fixtures. It’s something I had in mind for a while, but waiting for someone to collaborate on it who would use it themselves for production projects

**Comment by jasonkuhrt** [comment]
At Prisma we're just transitioning toward mocking gh API for our testing, but as we get more into it, we'll let you know any feedback we have!

**Comment by gr2m** [comment]
sounds great, please keep me posted 👍🏼 The aspect that I'm most interested in is to keep your http mocks up-to-date, that's what we do with the fixtures in this repository. They get re-recorded every night, and if any changes occur we get a pull request. There were a few accidental breaking changes we caught and reported to GitHub that way, but mostly its changes in headers and additional properties. In order to compare new fixtures to existing ones they need to be normalized, and we put a lot of work into that already, and can expand it if you would like to use that functionality for your fixtures, too

**Comment by gr2m** [comment]
I'll close the issue because there is nothing actionable left to do. Feel free to continue to comment if you have any follow up questions or ideas
